// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchRename(arg1, arg2) {
  return window['go']['main']['App']['BatchRename'](arg1, arg2);
}

export function GetFileInfos(arg1) {
  return window['go']['main']['App']['GetFileInfos'](arg1);
}

export function GetHomePath() {
  return window['go']['main']['App']['GetHomePath']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function PreviewRename(arg1, arg2) {
  return window['go']['main']['App']['PreviewRename'](arg1, arg2);
}

export function ResizeImages(arg1, arg2) {
  return window['go']['main']['App']['ResizeImages'](arg1, arg2);
}

export function ResizeImagesOnly(arg1, arg2) {
  return window['go']['main']['App']['ResizeImagesOnly'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
