// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {renamer} from '../models';
import {main} from '../models';
import {imager} from '../models';

export function BatchRename(arg1:Array<string>,arg2:Array<renamer.RenameRule>):Promise<Array<main.RenameResult>>;

export function GetFileInfos(arg1:Array<string>):Promise<Array<main.FileInfo>>;

export function GetHomePath():Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<main.DirEntry>>;

export function PreviewRename(arg1:Array<string>,arg2:Array<renamer.RenameRule>):Promise<Array<main.RenameResult>>;

export function ResizeImages(arg1:Array<string>,arg2:imager.ResizeConfig):Promise<Array<imager.ResizeResult>>;

export function ResizeImagesOnly(arg1:Array<string>,arg2:imager.ResizeConfig):Promise<Array<imager.ResizeResult>>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;
